name: monkeyz-frontend
services:
- name: frontend
  github:
    branch: main
    deploy_on_push: true
  source_dir: .
  build_command: bash ./do-build.sh
  run_command: bash ./do-run.sh
  http_port: 8080
  instance_size_slug: basic-xs
  health_check:
    http_path: /health.json
    port: 8080
    initial_delay_seconds: 10
    period_seconds: 5
  routes:
  - path: /
  envs:
  - key: REACT_APP_PATH_BACKEND
    scope: BUILD_TIME
    value: \
  - key: REACT_APP_GOOGLE_CLIENT_ID
    scope: BUILD_TIME
    value: \
    type: SECRET
  - key: REACT_APP_EMAILJS_PUBLIC_KEY
    scope: BUILD_TIME
    value: \
    type: SECRET
  - key: REACT_APP_EMAILJS_SERVICE_ID
    scope: BUILD_TIME
    value: \
  - key: REACT_APP_EMAILJS_RESET_TEMPLATE
    scope: BUILD_TIME
    value: \
  - key: REACT_APP_EMAILJS_OTP_TEMPLATE
    scope: BUILD_TIME
    value: \
  - key: REACT_APP_EMAILJS_WELCOME_TEMP
    scope: BUILD_TIME
    value: \
  - key: REACT_APP_PAYMENT_FAIL_URL
    scope: BUILD_TIME
    value: \/fail
  - key: REACT_APP_PAYMENT_SUCCESS_URL
    scope: BUILD_TIME
    value: \/success
  - key: REACT_APP_GROW_API_KEY
    scope: BUILD_TIME
    value: \
    type: SECRET
