name: frontend
region: fra
services:
- environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: EvyaIL/CDMonkey
  http_port: 8080
  instance_count: 2
  instance_size_slug: apps-s-1vcpu-1gb
  name: cdmonkey-frontend
  build_command: npm run build
  run_command: npm start
  source_dir: frontend
  health_check:
    http_path: /health.json
    port: 8080
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  routes:
  - path: /
  envs:
  - key: REACT_APP_PATH_BACKEND
    scope: BUILD_TIME
    value: \
  - key: REACT_APP_GOOGLE_CLIENT_ID
    scope: BUILD_TIME
    value: \
    type: SECRET
  - key: REACT_APP_EMAILJS_PUBLIC_KEY
    scope: BUILD_TIME
    value: \
    type: SECRET
  - key: REACT_APP_EMAILJS_SERVICE_ID
    scope: BUILD_TIME
    value: \
  - key: REACT_APP_EMAILJS_RESET_TEMPLATE
    scope: BUILD_TIME
    value: \
  - key: REACT_APP_EMAILJS_OTP_TEMPLATE
    scope: BUILD_TIME
    value: \
  - key: REACT_APP_EMAILJS_WELCOME_TEMP
    scope: BUILD_TIME
    value: \
  - key: REACT_APP_PAYMENT_FAIL_URL
    scope: BUILD_TIME
    value: \/fail
  - key: REACT_APP_PAYMENT_SUCCESS_URL
    scope: BUILD_TIME
    value: \/success
  - key: REACT_APP_GROW_API_KEY
    scope: BUILD_TIME
    value: \
    type: SECRET
