services:
- environment_slug: node-js
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${mongodb1.DATABASE_URL}
  - key: CA_CERT
    scope: RUN_TIME
    value: ${mongodb1.CA_CERT}
  github:
    branch: main
    deploy_on_push: true
    repo: EvyaIL/CDMonkey
  http_port: 8080
  instance_count: 2
  instance_size_slug: apps-s-1vcpu-1gb
  name: cdmonkey-frontend
  build_command: npm install && npm run build
  run_command: node server.js
  source_dir: frontend
  health_check:
    http_path: /health.json
    port: 8080
    initial_delay_seconds: 40
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3